version: "2"
services:
  tomcat:
    build:
      context: .
    container_name: tomcat
    image: livingstoneonline/tomcat
    environment:
      - TOMCAT_ADMIN_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - FEDORA_DB_PASSWORD=password
      - FEDORA_ADMIN_PASSWORD=password
      - FEDORA_INTERNAL_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: livingstoneonline/mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
