[template]
src = "fedora-users.xml.tmpl"
dest = "/opt/fedora/server/config/fedora-users.xml"
prefix= "/fedora"
uid = 105
gid = 1000
mode="0644"
keys = ["/admin/user", "/admin/password", "/internal/password"]