[template]
src = "repository.properties.tmpl"
dest = "/opt/tomcat/webapps/fedoragsearch/WEB-INF/classes/fgsconfigFinal/repository/FgsRepos/repository.properties"
prefix= "/fedora"
uid = 105
gid = 1000
mode="0644"
keys = ["/host", "/host/port", "/admin/user", "/admin/password"]